### ISSUE TITLE
Missing SVG Perl module

### ISSUE THREAD

**Issue by pditommaso** [satta/annot-nf#1]
The Circos task is returning the following error message 

	Error executing process > 'circos_run_chrs (1)'

	Caused by:
	  Missing output file(s): 'image.png' expected by process: circos_run_chrs (1)

	Command executed:

	  circos  -conf /opt/data/circos/circos.debian.conf -param image/file=image.png                  -param chromosomes='LmjF.01;LDON_01'                 -param chromosomes_reverse=LmjF.01

	Command exit status:
	  0

	Command output:
  
	  *** REQUIRED MODULE(S) MISSING OR OUT-OF-DATE ***
  
	  You are missing one or more Perl modules, require newer versions, or some modules failed to load. Use CPAN to install it as described in this tutorial
  
	  http://www.circos.ca/documentation/tutorials/configuration/perl_and_modules
  
	  missing SVG
		error Can't locate SVG.pm in @INC (you may need to install the SVG module) (@INC contains: /usr/bin/lib /usr/bin/../lib /usr/bin /opt/ORTHOMCLV1.4/ /opt/RATT/ /opt/ABACAS2/ /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at (eval 60) line 1.

	Work dir:
	  /Users/pditommaso/scratch/de/24295ce116a4f938ae3f764954e4bd

**Comment by satta** [comment]
Thanks Paolo for reporting this. To track this down I would like to ask if you installed the dependencies yourself (what distro and how did you install them) or used the Docker containers from Docker hub?

**Comment by pditommaso** [comment]
I should have mentioned. It is raised when using the Docker image `satta/annot-nf`. So, I think, something is missing there.

**Comment by satta** [comment]
Hmmm, I was using this myself on my Mac a while ago... strange. Will investigate, thanks.

**Comment by satta** [comment]
Should be fixed now with 0897b2e1d677646b1d4b4c3bc7b2103d3b0fad22. Apparently the circos Debian package now does not list all of its dependencies...

**Comment by satta** [comment]
Docker hub images have been updated. You can try again if you want. The example completes for me:
```
[ss34@mib106184i:~/develop/annot-nf] ROOTDIR=`pwd` ../../nextflow -c loc_docker.config -c params_default.config run annot.nf -resume
N E X T F L O W  ~  version 0.14.1
Launching annot.nf
[warm up] executor > local
[00/7b6480] Cached process > contiguate_pseudochromosomes (1)
[ac/2585be] Cached process > press_ncRNA_cms (1)
...
[be/15b480] Submitted process > circos_run_chrs (1)
/Users/ss34/develop/annot-nf/work/tmp/20/d4bc5a0609b976ba50b88a7e0b3252/out.gaf
/Users/ss34/develop/annot-nf/work/be/15b48025d2971445cffd2c603ba5c6/image.png
```

**Comment by pditommaso** [comment]
Great! Not it works like a charm. BTW this is the biggest nextflow pipeline I have seen. Congrats.
